package com.example.dao;

import com.example.domain.DicSimOperator;
import java.util.List;

public interface DicSimOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    int insert(DicSimOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    DicSimOperator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    List<DicSimOperator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DicSimOperator record);
}