package com.example.dao;

import com.example.domain.NewDeviceInfo;
import java.util.List;

public interface NewDeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    int insert(NewDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    NewDeviceInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    List<NewDeviceInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewDeviceInfo record);
}