package com.example.domain;

import java.io.Serializable;

public class DicSimOperator implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.network_country_iso
     *
     * @mbggenerated
     */
    private String networkCountryIso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.network_operator
     *
     * @mbggenerated
     */
    private String networkOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.phone_type
     *
     * @mbggenerated
     */
    private String phoneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.sim_country_iso
     *
     * @mbggenerated
     */
    private String simCountryIso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.sim_operator
     *
     * @mbggenerated
     */
    private String simOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.sim_serial_number
     *
     * @mbggenerated
     */
    private String simSerialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sim_operator.subscriber_id
     *
     * @mbggenerated
     */
    private String subscriberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.id
     *
     * @return the value of dic_sim_operator.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.id
     *
     * @param id the value for dic_sim_operator.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.network_country_iso
     *
     * @return the value of dic_sim_operator.network_country_iso
     *
     * @mbggenerated
     */
    public String getNetworkCountryIso() {
        return networkCountryIso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.network_country_iso
     *
     * @param networkCountryIso the value for dic_sim_operator.network_country_iso
     *
     * @mbggenerated
     */
    public void setNetworkCountryIso(String networkCountryIso) {
        this.networkCountryIso = networkCountryIso == null ? null : networkCountryIso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.network_operator
     *
     * @return the value of dic_sim_operator.network_operator
     *
     * @mbggenerated
     */
    public String getNetworkOperator() {
        return networkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.network_operator
     *
     * @param networkOperator the value for dic_sim_operator.network_operator
     *
     * @mbggenerated
     */
    public void setNetworkOperator(String networkOperator) {
        this.networkOperator = networkOperator == null ? null : networkOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.phone_type
     *
     * @return the value of dic_sim_operator.phone_type
     *
     * @mbggenerated
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.phone_type
     *
     * @param phoneType the value for dic_sim_operator.phone_type
     *
     * @mbggenerated
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType == null ? null : phoneType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.sim_country_iso
     *
     * @return the value of dic_sim_operator.sim_country_iso
     *
     * @mbggenerated
     */
    public String getSimCountryIso() {
        return simCountryIso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.sim_country_iso
     *
     * @param simCountryIso the value for dic_sim_operator.sim_country_iso
     *
     * @mbggenerated
     */
    public void setSimCountryIso(String simCountryIso) {
        this.simCountryIso = simCountryIso == null ? null : simCountryIso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.sim_operator
     *
     * @return the value of dic_sim_operator.sim_operator
     *
     * @mbggenerated
     */
    public String getSimOperator() {
        return simOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.sim_operator
     *
     * @param simOperator the value for dic_sim_operator.sim_operator
     *
     * @mbggenerated
     */
    public void setSimOperator(String simOperator) {
        this.simOperator = simOperator == null ? null : simOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.sim_serial_number
     *
     * @return the value of dic_sim_operator.sim_serial_number
     *
     * @mbggenerated
     */
    public String getSimSerialNumber() {
        return simSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.sim_serial_number
     *
     * @param simSerialNumber the value for dic_sim_operator.sim_serial_number
     *
     * @mbggenerated
     */
    public void setSimSerialNumber(String simSerialNumber) {
        this.simSerialNumber = simSerialNumber == null ? null : simSerialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sim_operator.subscriber_id
     *
     * @return the value of dic_sim_operator.subscriber_id
     *
     * @mbggenerated
     */
    public String getSubscriberId() {
        return subscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sim_operator.subscriber_id
     *
     * @param subscriberId the value for dic_sim_operator.subscriber_id
     *
     * @mbggenerated
     */
    public void setSubscriberId(String subscriberId) {
        this.subscriberId = subscriberId == null ? null : subscriberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_sim_operator
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", networkCountryIso=").append(networkCountryIso);
        sb.append(", networkOperator=").append(networkOperator);
        sb.append(", phoneType=").append(phoneType);
        sb.append(", simCountryIso=").append(simCountryIso);
        sb.append(", simOperator=").append(simOperator);
        sb.append(", simSerialNumber=").append(simSerialNumber);
        sb.append(", subscriberId=").append(subscriberId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}