package com.example.domain;

import java.io.Serializable;

public class NewDeviceInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.device_info_id
     *
     * @mbggenerated
     */
    private Long deviceInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.device_id2
     *
     * @mbggenerated
     */
    private String deviceId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.block_count
     *
     * @mbggenerated
     */
    private String blockCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sim_serial_number
     *
     * @mbggenerated
     */
    private String simSerialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.cup_name
     *
     * @mbggenerated
     */
    private String cupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.radio_version
     *
     * @mbggenerated
     */
    private String radioVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.mac_address
     *
     * @mbggenerated
     */
    private String macAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.network_id
     *
     * @mbggenerated
     */
    private String networkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.network_operator_name
     *
     * @mbggenerated
     */
    private String networkOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.network_operator
     *
     * @mbggenerated
     */
    private String networkOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.phone_type
     *
     * @mbggenerated
     */
    private String phoneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.ssid
     *
     * @mbggenerated
     */
    private String ssid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sim_operator_name
     *
     * @mbggenerated
     */
    private String simOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.base_station_id
     *
     * @mbggenerated
     */
    private String baseStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.width
     *
     * @mbggenerated
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sim_state
     *
     * @mbggenerated
     */
    private String simState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.lac
     *
     * @mbggenerated
     */
    private String lac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.subscriber_id
     *
     * @mbggenerated
     */
    private String subscriberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sim_operator
     *
     * @mbggenerated
     */
    private String simOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.c_id
     *
     * @mbggenerated
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.network_country_iso
     *
     * @mbggenerated
     */
    private String networkCountryIso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sim_country_iso
     *
     * @mbggenerated
     */
    private String simCountryIso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.network_type
     *
     * @mbggenerated
     */
    private String networkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.subtype_name
     *
     * @mbggenerated
     */
    private String subtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.b_ssid
     *
     * @mbggenerated
     */
    private String bSsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.string
     *
     * @mbggenerated
     */
    private String string;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.bluetooth_name
     *
     * @mbggenerated
     */
    private String bluetoothName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.bluetooth_address
     *
     * @mbggenerated
     */
    private String bluetoothAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.subscriber_id2
     *
     * @mbggenerated
     */
    private String subscriberId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.cpuinfo_max_freq
     *
     * @mbggenerated
     */
    private String cpuinfoMaxFreq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.user_agent
     *
     * @mbggenerated
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.densitydpi
     *
     * @mbggenerated
     */
    private String densitydpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.gl_renderer
     *
     * @mbggenerated
     */
    private String glRenderer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.gl_vendor
     *
     * @mbggenerated
     */
    private String glVendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.gl_version
     *
     * @mbggenerated
     */
    private String glVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.type_gyroscope
     *
     * @mbggenerated
     */
    private String typeGyroscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.type_gravity
     *
     * @mbggenerated
     */
    private String typeGravity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.type_ambient_temperature
     *
     * @mbggenerated
     */
    private String typeAmbientTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.camera_back
     *
     * @mbggenerated
     */
    private String cameraBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.camera_front
     *
     * @mbggenerated
     */
    private String cameraFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.board
     *
     * @mbggenerated
     */
    private String board;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.bootloader
     *
     * @mbggenerated
     */
    private String bootloader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.cpu_abi
     *
     * @mbggenerated
     */
    private String cpuAbi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.cpu_abi2
     *
     * @mbggenerated
     */
    private String cpuAbi2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.device
     *
     * @mbggenerated
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.display
     *
     * @mbggenerated
     */
    private String display;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.fingerprint
     *
     * @mbggenerated
     */
    private String fingerprint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.hardware
     *
     * @mbggenerated
     */
    private String hardware;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.host
     *
     * @mbggenerated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.string_id
     *
     * @mbggenerated
     */
    private String stringId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.product
     *
     * @mbggenerated
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.radio
     *
     * @mbggenerated
     */
    private String radio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.serial
     *
     * @mbggenerated
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.unknown
     *
     * @mbggenerated
     */
    private String unknown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sdk
     *
     * @mbggenerated
     */
    private String sdk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sdk_int
     *
     * @mbggenerated
     */
    private String sdkInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sd_size
     *
     * @mbggenerated
     */
    private String sdSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.memory_size
     *
     * @mbggenerated
     */
    private String memorySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.create_at
     *
     * @mbggenerated
     */
    private String createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.update_at
     *
     * @mbggenerated
     */
    private String updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.memory_info
     *
     * @mbggenerated
     */
    private String memoryInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.cpu_info
     *
     * @mbggenerated
     */
    private String cpuInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sd_type
     *
     * @mbggenerated
     */
    private String sdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sd_name
     *
     * @mbggenerated
     */
    private String sdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_device_info.sd_cid
     *
     * @mbggenerated
     */
    private String sdCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.id
     *
     * @return the value of new_device_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.id
     *
     * @param id the value for new_device_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.device_info_id
     *
     * @return the value of new_device_info.device_info_id
     *
     * @mbggenerated
     */
    public Long getDeviceInfoId() {
        return deviceInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.device_info_id
     *
     * @param deviceInfoId the value for new_device_info.device_info_id
     *
     * @mbggenerated
     */
    public void setDeviceInfoId(Long deviceInfoId) {
        this.deviceInfoId = deviceInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.manufacturer
     *
     * @return the value of new_device_info.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.manufacturer
     *
     * @param manufacturer the value for new_device_info.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.model
     *
     * @return the value of new_device_info.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.model
     *
     * @param model the value for new_device_info.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.device_id
     *
     * @return the value of new_device_info.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.device_id
     *
     * @param deviceId the value for new_device_info.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.device_id2
     *
     * @return the value of new_device_info.device_id2
     *
     * @mbggenerated
     */
    public String getDeviceId2() {
        return deviceId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.device_id2
     *
     * @param deviceId2 the value for new_device_info.device_id2
     *
     * @mbggenerated
     */
    public void setDeviceId2(String deviceId2) {
        this.deviceId2 = deviceId2 == null ? null : deviceId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.channel
     *
     * @return the value of new_device_info.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.channel
     *
     * @param channel the value for new_device_info.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.block_count
     *
     * @return the value of new_device_info.block_count
     *
     * @mbggenerated
     */
    public String getBlockCount() {
        return blockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.block_count
     *
     * @param blockCount the value for new_device_info.block_count
     *
     * @mbggenerated
     */
    public void setBlockCount(String blockCount) {
        this.blockCount = blockCount == null ? null : blockCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sim_serial_number
     *
     * @return the value of new_device_info.sim_serial_number
     *
     * @mbggenerated
     */
    public String getSimSerialNumber() {
        return simSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sim_serial_number
     *
     * @param simSerialNumber the value for new_device_info.sim_serial_number
     *
     * @mbggenerated
     */
    public void setSimSerialNumber(String simSerialNumber) {
        this.simSerialNumber = simSerialNumber == null ? null : simSerialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.cup_name
     *
     * @return the value of new_device_info.cup_name
     *
     * @mbggenerated
     */
    public String getCupName() {
        return cupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.cup_name
     *
     * @param cupName the value for new_device_info.cup_name
     *
     * @mbggenerated
     */
    public void setCupName(String cupName) {
        this.cupName = cupName == null ? null : cupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.radio_version
     *
     * @return the value of new_device_info.radio_version
     *
     * @mbggenerated
     */
    public String getRadioVersion() {
        return radioVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.radio_version
     *
     * @param radioVersion the value for new_device_info.radio_version
     *
     * @mbggenerated
     */
    public void setRadioVersion(String radioVersion) {
        this.radioVersion = radioVersion == null ? null : radioVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.mac_address
     *
     * @return the value of new_device_info.mac_address
     *
     * @mbggenerated
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.mac_address
     *
     * @param macAddress the value for new_device_info.mac_address
     *
     * @mbggenerated
     */
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress == null ? null : macAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.network_id
     *
     * @return the value of new_device_info.network_id
     *
     * @mbggenerated
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.network_id
     *
     * @param networkId the value for new_device_info.network_id
     *
     * @mbggenerated
     */
    public void setNetworkId(String networkId) {
        this.networkId = networkId == null ? null : networkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.network_operator_name
     *
     * @return the value of new_device_info.network_operator_name
     *
     * @mbggenerated
     */
    public String getNetworkOperatorName() {
        return networkOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.network_operator_name
     *
     * @param networkOperatorName the value for new_device_info.network_operator_name
     *
     * @mbggenerated
     */
    public void setNetworkOperatorName(String networkOperatorName) {
        this.networkOperatorName = networkOperatorName == null ? null : networkOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.network_operator
     *
     * @return the value of new_device_info.network_operator
     *
     * @mbggenerated
     */
    public String getNetworkOperator() {
        return networkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.network_operator
     *
     * @param networkOperator the value for new_device_info.network_operator
     *
     * @mbggenerated
     */
    public void setNetworkOperator(String networkOperator) {
        this.networkOperator = networkOperator == null ? null : networkOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.phone_type
     *
     * @return the value of new_device_info.phone_type
     *
     * @mbggenerated
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.phone_type
     *
     * @param phoneType the value for new_device_info.phone_type
     *
     * @mbggenerated
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType == null ? null : phoneType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.height
     *
     * @return the value of new_device_info.height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.height
     *
     * @param height the value for new_device_info.height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.ssid
     *
     * @return the value of new_device_info.ssid
     *
     * @mbggenerated
     */
    public String getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.ssid
     *
     * @param ssid the value for new_device_info.ssid
     *
     * @mbggenerated
     */
    public void setSsid(String ssid) {
        this.ssid = ssid == null ? null : ssid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sim_operator_name
     *
     * @return the value of new_device_info.sim_operator_name
     *
     * @mbggenerated
     */
    public String getSimOperatorName() {
        return simOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sim_operator_name
     *
     * @param simOperatorName the value for new_device_info.sim_operator_name
     *
     * @mbggenerated
     */
    public void setSimOperatorName(String simOperatorName) {
        this.simOperatorName = simOperatorName == null ? null : simOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.base_station_id
     *
     * @return the value of new_device_info.base_station_id
     *
     * @mbggenerated
     */
    public String getBaseStationId() {
        return baseStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.base_station_id
     *
     * @param baseStationId the value for new_device_info.base_station_id
     *
     * @mbggenerated
     */
    public void setBaseStationId(String baseStationId) {
        this.baseStationId = baseStationId == null ? null : baseStationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.width
     *
     * @return the value of new_device_info.width
     *
     * @mbggenerated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.width
     *
     * @param width the value for new_device_info.width
     *
     * @mbggenerated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sim_state
     *
     * @return the value of new_device_info.sim_state
     *
     * @mbggenerated
     */
    public String getSimState() {
        return simState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sim_state
     *
     * @param simState the value for new_device_info.sim_state
     *
     * @mbggenerated
     */
    public void setSimState(String simState) {
        this.simState = simState == null ? null : simState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.lac
     *
     * @return the value of new_device_info.lac
     *
     * @mbggenerated
     */
    public String getLac() {
        return lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.lac
     *
     * @param lac the value for new_device_info.lac
     *
     * @mbggenerated
     */
    public void setLac(String lac) {
        this.lac = lac == null ? null : lac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.address
     *
     * @return the value of new_device_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.address
     *
     * @param address the value for new_device_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.subscriber_id
     *
     * @return the value of new_device_info.subscriber_id
     *
     * @mbggenerated
     */
    public String getSubscriberId() {
        return subscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.subscriber_id
     *
     * @param subscriberId the value for new_device_info.subscriber_id
     *
     * @mbggenerated
     */
    public void setSubscriberId(String subscriberId) {
        this.subscriberId = subscriberId == null ? null : subscriberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sim_operator
     *
     * @return the value of new_device_info.sim_operator
     *
     * @mbggenerated
     */
    public String getSimOperator() {
        return simOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sim_operator
     *
     * @param simOperator the value for new_device_info.sim_operator
     *
     * @mbggenerated
     */
    public void setSimOperator(String simOperator) {
        this.simOperator = simOperator == null ? null : simOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.c_id
     *
     * @return the value of new_device_info.c_id
     *
     * @mbggenerated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.c_id
     *
     * @param cId the value for new_device_info.c_id
     *
     * @mbggenerated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.network_country_iso
     *
     * @return the value of new_device_info.network_country_iso
     *
     * @mbggenerated
     */
    public String getNetworkCountryIso() {
        return networkCountryIso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.network_country_iso
     *
     * @param networkCountryIso the value for new_device_info.network_country_iso
     *
     * @mbggenerated
     */
    public void setNetworkCountryIso(String networkCountryIso) {
        this.networkCountryIso = networkCountryIso == null ? null : networkCountryIso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sim_country_iso
     *
     * @return the value of new_device_info.sim_country_iso
     *
     * @mbggenerated
     */
    public String getSimCountryIso() {
        return simCountryIso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sim_country_iso
     *
     * @param simCountryIso the value for new_device_info.sim_country_iso
     *
     * @mbggenerated
     */
    public void setSimCountryIso(String simCountryIso) {
        this.simCountryIso = simCountryIso == null ? null : simCountryIso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.network_type
     *
     * @return the value of new_device_info.network_type
     *
     * @mbggenerated
     */
    public String getNetworkType() {
        return networkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.network_type
     *
     * @param networkType the value for new_device_info.network_type
     *
     * @mbggenerated
     */
    public void setNetworkType(String networkType) {
        this.networkType = networkType == null ? null : networkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.subtype_name
     *
     * @return the value of new_device_info.subtype_name
     *
     * @mbggenerated
     */
    public String getSubtypeName() {
        return subtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.subtype_name
     *
     * @param subtypeName the value for new_device_info.subtype_name
     *
     * @mbggenerated
     */
    public void setSubtypeName(String subtypeName) {
        this.subtypeName = subtypeName == null ? null : subtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.b_ssid
     *
     * @return the value of new_device_info.b_ssid
     *
     * @mbggenerated
     */
    public String getbSsid() {
        return bSsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.b_ssid
     *
     * @param bSsid the value for new_device_info.b_ssid
     *
     * @mbggenerated
     */
    public void setbSsid(String bSsid) {
        this.bSsid = bSsid == null ? null : bSsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.string
     *
     * @return the value of new_device_info.string
     *
     * @mbggenerated
     */
    public String getString() {
        return string;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.string
     *
     * @param string the value for new_device_info.string
     *
     * @mbggenerated
     */
    public void setString(String string) {
        this.string = string == null ? null : string.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.bluetooth_name
     *
     * @return the value of new_device_info.bluetooth_name
     *
     * @mbggenerated
     */
    public String getBluetoothName() {
        return bluetoothName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.bluetooth_name
     *
     * @param bluetoothName the value for new_device_info.bluetooth_name
     *
     * @mbggenerated
     */
    public void setBluetoothName(String bluetoothName) {
        this.bluetoothName = bluetoothName == null ? null : bluetoothName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.bluetooth_address
     *
     * @return the value of new_device_info.bluetooth_address
     *
     * @mbggenerated
     */
    public String getBluetoothAddress() {
        return bluetoothAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.bluetooth_address
     *
     * @param bluetoothAddress the value for new_device_info.bluetooth_address
     *
     * @mbggenerated
     */
    public void setBluetoothAddress(String bluetoothAddress) {
        this.bluetoothAddress = bluetoothAddress == null ? null : bluetoothAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.subscriber_id2
     *
     * @return the value of new_device_info.subscriber_id2
     *
     * @mbggenerated
     */
    public String getSubscriberId2() {
        return subscriberId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.subscriber_id2
     *
     * @param subscriberId2 the value for new_device_info.subscriber_id2
     *
     * @mbggenerated
     */
    public void setSubscriberId2(String subscriberId2) {
        this.subscriberId2 = subscriberId2 == null ? null : subscriberId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.cpuinfo_max_freq
     *
     * @return the value of new_device_info.cpuinfo_max_freq
     *
     * @mbggenerated
     */
    public String getCpuinfoMaxFreq() {
        return cpuinfoMaxFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.cpuinfo_max_freq
     *
     * @param cpuinfoMaxFreq the value for new_device_info.cpuinfo_max_freq
     *
     * @mbggenerated
     */
    public void setCpuinfoMaxFreq(String cpuinfoMaxFreq) {
        this.cpuinfoMaxFreq = cpuinfoMaxFreq == null ? null : cpuinfoMaxFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.user_agent
     *
     * @return the value of new_device_info.user_agent
     *
     * @mbggenerated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.user_agent
     *
     * @param userAgent the value for new_device_info.user_agent
     *
     * @mbggenerated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.version
     *
     * @return the value of new_device_info.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.version
     *
     * @param version the value for new_device_info.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.densitydpi
     *
     * @return the value of new_device_info.densitydpi
     *
     * @mbggenerated
     */
    public String getDensitydpi() {
        return densitydpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.densitydpi
     *
     * @param densitydpi the value for new_device_info.densitydpi
     *
     * @mbggenerated
     */
    public void setDensitydpi(String densitydpi) {
        this.densitydpi = densitydpi == null ? null : densitydpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.gl_renderer
     *
     * @return the value of new_device_info.gl_renderer
     *
     * @mbggenerated
     */
    public String getGlRenderer() {
        return glRenderer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.gl_renderer
     *
     * @param glRenderer the value for new_device_info.gl_renderer
     *
     * @mbggenerated
     */
    public void setGlRenderer(String glRenderer) {
        this.glRenderer = glRenderer == null ? null : glRenderer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.gl_vendor
     *
     * @return the value of new_device_info.gl_vendor
     *
     * @mbggenerated
     */
    public String getGlVendor() {
        return glVendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.gl_vendor
     *
     * @param glVendor the value for new_device_info.gl_vendor
     *
     * @mbggenerated
     */
    public void setGlVendor(String glVendor) {
        this.glVendor = glVendor == null ? null : glVendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.gl_version
     *
     * @return the value of new_device_info.gl_version
     *
     * @mbggenerated
     */
    public String getGlVersion() {
        return glVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.gl_version
     *
     * @param glVersion the value for new_device_info.gl_version
     *
     * @mbggenerated
     */
    public void setGlVersion(String glVersion) {
        this.glVersion = glVersion == null ? null : glVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.type_gyroscope
     *
     * @return the value of new_device_info.type_gyroscope
     *
     * @mbggenerated
     */
    public String getTypeGyroscope() {
        return typeGyroscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.type_gyroscope
     *
     * @param typeGyroscope the value for new_device_info.type_gyroscope
     *
     * @mbggenerated
     */
    public void setTypeGyroscope(String typeGyroscope) {
        this.typeGyroscope = typeGyroscope == null ? null : typeGyroscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.type_gravity
     *
     * @return the value of new_device_info.type_gravity
     *
     * @mbggenerated
     */
    public String getTypeGravity() {
        return typeGravity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.type_gravity
     *
     * @param typeGravity the value for new_device_info.type_gravity
     *
     * @mbggenerated
     */
    public void setTypeGravity(String typeGravity) {
        this.typeGravity = typeGravity == null ? null : typeGravity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.type_ambient_temperature
     *
     * @return the value of new_device_info.type_ambient_temperature
     *
     * @mbggenerated
     */
    public String getTypeAmbientTemperature() {
        return typeAmbientTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.type_ambient_temperature
     *
     * @param typeAmbientTemperature the value for new_device_info.type_ambient_temperature
     *
     * @mbggenerated
     */
    public void setTypeAmbientTemperature(String typeAmbientTemperature) {
        this.typeAmbientTemperature = typeAmbientTemperature == null ? null : typeAmbientTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.camera_back
     *
     * @return the value of new_device_info.camera_back
     *
     * @mbggenerated
     */
    public String getCameraBack() {
        return cameraBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.camera_back
     *
     * @param cameraBack the value for new_device_info.camera_back
     *
     * @mbggenerated
     */
    public void setCameraBack(String cameraBack) {
        this.cameraBack = cameraBack == null ? null : cameraBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.camera_front
     *
     * @return the value of new_device_info.camera_front
     *
     * @mbggenerated
     */
    public String getCameraFront() {
        return cameraFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.camera_front
     *
     * @param cameraFront the value for new_device_info.camera_front
     *
     * @mbggenerated
     */
    public void setCameraFront(String cameraFront) {
        this.cameraFront = cameraFront == null ? null : cameraFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.board
     *
     * @return the value of new_device_info.board
     *
     * @mbggenerated
     */
    public String getBoard() {
        return board;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.board
     *
     * @param board the value for new_device_info.board
     *
     * @mbggenerated
     */
    public void setBoard(String board) {
        this.board = board == null ? null : board.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.bootloader
     *
     * @return the value of new_device_info.bootloader
     *
     * @mbggenerated
     */
    public String getBootloader() {
        return bootloader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.bootloader
     *
     * @param bootloader the value for new_device_info.bootloader
     *
     * @mbggenerated
     */
    public void setBootloader(String bootloader) {
        this.bootloader = bootloader == null ? null : bootloader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.brand
     *
     * @return the value of new_device_info.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.brand
     *
     * @param brand the value for new_device_info.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.cpu_abi
     *
     * @return the value of new_device_info.cpu_abi
     *
     * @mbggenerated
     */
    public String getCpuAbi() {
        return cpuAbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.cpu_abi
     *
     * @param cpuAbi the value for new_device_info.cpu_abi
     *
     * @mbggenerated
     */
    public void setCpuAbi(String cpuAbi) {
        this.cpuAbi = cpuAbi == null ? null : cpuAbi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.cpu_abi2
     *
     * @return the value of new_device_info.cpu_abi2
     *
     * @mbggenerated
     */
    public String getCpuAbi2() {
        return cpuAbi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.cpu_abi2
     *
     * @param cpuAbi2 the value for new_device_info.cpu_abi2
     *
     * @mbggenerated
     */
    public void setCpuAbi2(String cpuAbi2) {
        this.cpuAbi2 = cpuAbi2 == null ? null : cpuAbi2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.device
     *
     * @return the value of new_device_info.device
     *
     * @mbggenerated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.device
     *
     * @param device the value for new_device_info.device
     *
     * @mbggenerated
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.display
     *
     * @return the value of new_device_info.display
     *
     * @mbggenerated
     */
    public String getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.display
     *
     * @param display the value for new_device_info.display
     *
     * @mbggenerated
     */
    public void setDisplay(String display) {
        this.display = display == null ? null : display.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.fingerprint
     *
     * @return the value of new_device_info.fingerprint
     *
     * @mbggenerated
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.fingerprint
     *
     * @param fingerprint the value for new_device_info.fingerprint
     *
     * @mbggenerated
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint == null ? null : fingerprint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.hardware
     *
     * @return the value of new_device_info.hardware
     *
     * @mbggenerated
     */
    public String getHardware() {
        return hardware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.hardware
     *
     * @param hardware the value for new_device_info.hardware
     *
     * @mbggenerated
     */
    public void setHardware(String hardware) {
        this.hardware = hardware == null ? null : hardware.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.host
     *
     * @return the value of new_device_info.host
     *
     * @mbggenerated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.host
     *
     * @param host the value for new_device_info.host
     *
     * @mbggenerated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.string_id
     *
     * @return the value of new_device_info.string_id
     *
     * @mbggenerated
     */
    public String getStringId() {
        return stringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.string_id
     *
     * @param stringId the value for new_device_info.string_id
     *
     * @mbggenerated
     */
    public void setStringId(String stringId) {
        this.stringId = stringId == null ? null : stringId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.product
     *
     * @return the value of new_device_info.product
     *
     * @mbggenerated
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.product
     *
     * @param product the value for new_device_info.product
     *
     * @mbggenerated
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.radio
     *
     * @return the value of new_device_info.radio
     *
     * @mbggenerated
     */
    public String getRadio() {
        return radio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.radio
     *
     * @param radio the value for new_device_info.radio
     *
     * @mbggenerated
     */
    public void setRadio(String radio) {
        this.radio = radio == null ? null : radio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.type
     *
     * @return the value of new_device_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.type
     *
     * @param type the value for new_device_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.serial
     *
     * @return the value of new_device_info.serial
     *
     * @mbggenerated
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.serial
     *
     * @param serial the value for new_device_info.serial
     *
     * @mbggenerated
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.tags
     *
     * @return the value of new_device_info.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.tags
     *
     * @param tags the value for new_device_info.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.unknown
     *
     * @return the value of new_device_info.unknown
     *
     * @mbggenerated
     */
    public String getUnknown() {
        return unknown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.unknown
     *
     * @param unknown the value for new_device_info.unknown
     *
     * @mbggenerated
     */
    public void setUnknown(String unknown) {
        this.unknown = unknown == null ? null : unknown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.user
     *
     * @return the value of new_device_info.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.user
     *
     * @param user the value for new_device_info.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sdk
     *
     * @return the value of new_device_info.sdk
     *
     * @mbggenerated
     */
    public String getSdk() {
        return sdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sdk
     *
     * @param sdk the value for new_device_info.sdk
     *
     * @mbggenerated
     */
    public void setSdk(String sdk) {
        this.sdk = sdk == null ? null : sdk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sdk_int
     *
     * @return the value of new_device_info.sdk_int
     *
     * @mbggenerated
     */
    public String getSdkInt() {
        return sdkInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sdk_int
     *
     * @param sdkInt the value for new_device_info.sdk_int
     *
     * @mbggenerated
     */
    public void setSdkInt(String sdkInt) {
        this.sdkInt = sdkInt == null ? null : sdkInt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sd_size
     *
     * @return the value of new_device_info.sd_size
     *
     * @mbggenerated
     */
    public String getSdSize() {
        return sdSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sd_size
     *
     * @param sdSize the value for new_device_info.sd_size
     *
     * @mbggenerated
     */
    public void setSdSize(String sdSize) {
        this.sdSize = sdSize == null ? null : sdSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.memory_size
     *
     * @return the value of new_device_info.memory_size
     *
     * @mbggenerated
     */
    public String getMemorySize() {
        return memorySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.memory_size
     *
     * @param memorySize the value for new_device_info.memory_size
     *
     * @mbggenerated
     */
    public void setMemorySize(String memorySize) {
        this.memorySize = memorySize == null ? null : memorySize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.create_at
     *
     * @return the value of new_device_info.create_at
     *
     * @mbggenerated
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.create_at
     *
     * @param createAt the value for new_device_info.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.update_at
     *
     * @return the value of new_device_info.update_at
     *
     * @mbggenerated
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.update_at
     *
     * @param updateAt the value for new_device_info.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.memory_info
     *
     * @return the value of new_device_info.memory_info
     *
     * @mbggenerated
     */
    public String getMemoryInfo() {
        return memoryInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.memory_info
     *
     * @param memoryInfo the value for new_device_info.memory_info
     *
     * @mbggenerated
     */
    public void setMemoryInfo(String memoryInfo) {
        this.memoryInfo = memoryInfo == null ? null : memoryInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.cpu_info
     *
     * @return the value of new_device_info.cpu_info
     *
     * @mbggenerated
     */
    public String getCpuInfo() {
        return cpuInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.cpu_info
     *
     * @param cpuInfo the value for new_device_info.cpu_info
     *
     * @mbggenerated
     */
    public void setCpuInfo(String cpuInfo) {
        this.cpuInfo = cpuInfo == null ? null : cpuInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sd_type
     *
     * @return the value of new_device_info.sd_type
     *
     * @mbggenerated
     */
    public String getSdType() {
        return sdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sd_type
     *
     * @param sdType the value for new_device_info.sd_type
     *
     * @mbggenerated
     */
    public void setSdType(String sdType) {
        this.sdType = sdType == null ? null : sdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sd_name
     *
     * @return the value of new_device_info.sd_name
     *
     * @mbggenerated
     */
    public String getSdName() {
        return sdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sd_name
     *
     * @param sdName the value for new_device_info.sd_name
     *
     * @mbggenerated
     */
    public void setSdName(String sdName) {
        this.sdName = sdName == null ? null : sdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_device_info.sd_cid
     *
     * @return the value of new_device_info.sd_cid
     *
     * @mbggenerated
     */
    public String getSdCid() {
        return sdCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_device_info.sd_cid
     *
     * @param sdCid the value for new_device_info.sd_cid
     *
     * @mbggenerated
     */
    public void setSdCid(String sdCid) {
        this.sdCid = sdCid == null ? null : sdCid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_device_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceInfoId=").append(deviceInfoId);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", model=").append(model);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceId2=").append(deviceId2);
        sb.append(", channel=").append(channel);
        sb.append(", blockCount=").append(blockCount);
        sb.append(", simSerialNumber=").append(simSerialNumber);
        sb.append(", cupName=").append(cupName);
        sb.append(", radioVersion=").append(radioVersion);
        sb.append(", macAddress=").append(macAddress);
        sb.append(", networkId=").append(networkId);
        sb.append(", networkOperatorName=").append(networkOperatorName);
        sb.append(", networkOperator=").append(networkOperator);
        sb.append(", phoneType=").append(phoneType);
        sb.append(", height=").append(height);
        sb.append(", ssid=").append(ssid);
        sb.append(", simOperatorName=").append(simOperatorName);
        sb.append(", baseStationId=").append(baseStationId);
        sb.append(", width=").append(width);
        sb.append(", simState=").append(simState);
        sb.append(", lac=").append(lac);
        sb.append(", address=").append(address);
        sb.append(", subscriberId=").append(subscriberId);
        sb.append(", simOperator=").append(simOperator);
        sb.append(", cId=").append(cId);
        sb.append(", networkCountryIso=").append(networkCountryIso);
        sb.append(", simCountryIso=").append(simCountryIso);
        sb.append(", networkType=").append(networkType);
        sb.append(", subtypeName=").append(subtypeName);
        sb.append(", bSsid=").append(bSsid);
        sb.append(", string=").append(string);
        sb.append(", bluetoothName=").append(bluetoothName);
        sb.append(", bluetoothAddress=").append(bluetoothAddress);
        sb.append(", subscriberId2=").append(subscriberId2);
        sb.append(", cpuinfoMaxFreq=").append(cpuinfoMaxFreq);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", version=").append(version);
        sb.append(", densitydpi=").append(densitydpi);
        sb.append(", glRenderer=").append(glRenderer);
        sb.append(", glVendor=").append(glVendor);
        sb.append(", glVersion=").append(glVersion);
        sb.append(", typeGyroscope=").append(typeGyroscope);
        sb.append(", typeGravity=").append(typeGravity);
        sb.append(", typeAmbientTemperature=").append(typeAmbientTemperature);
        sb.append(", cameraBack=").append(cameraBack);
        sb.append(", cameraFront=").append(cameraFront);
        sb.append(", board=").append(board);
        sb.append(", bootloader=").append(bootloader);
        sb.append(", brand=").append(brand);
        sb.append(", cpuAbi=").append(cpuAbi);
        sb.append(", cpuAbi2=").append(cpuAbi2);
        sb.append(", device=").append(device);
        sb.append(", display=").append(display);
        sb.append(", fingerprint=").append(fingerprint);
        sb.append(", hardware=").append(hardware);
        sb.append(", host=").append(host);
        sb.append(", stringId=").append(stringId);
        sb.append(", product=").append(product);
        sb.append(", radio=").append(radio);
        sb.append(", type=").append(type);
        sb.append(", serial=").append(serial);
        sb.append(", tags=").append(tags);
        sb.append(", unknown=").append(unknown);
        sb.append(", user=").append(user);
        sb.append(", sdk=").append(sdk);
        sb.append(", sdkInt=").append(sdkInt);
        sb.append(", sdSize=").append(sdSize);
        sb.append(", memorySize=").append(memorySize);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", memoryInfo=").append(memoryInfo);
        sb.append(", cpuInfo=").append(cpuInfo);
        sb.append(", sdType=").append(sdType);
        sb.append(", sdName=").append(sdName);
        sb.append(", sdCid=").append(sdCid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}